### ISSUE TITLE
Just wondering why did you choose podman for that?

### ISSUE THREAD

**Issue by lemanschik** [grzegorzk/vscode_in_podman#2]
Why did you not choose some os specific tool like appamor to turn of the networking for that app directly without repackageing it?

**Comment by grzegorzk** [comment]
@lemanschik - mainly because podman does not involve utilizing docker-like daemon, I like podman because I can run real unprivileged containers without having other system accounts involved. But if you prefer Docker then simply run it like this: `make run DOCKER=docker`

**Comment by lemanschik** [comment]
@grzegorzk no i am working on vscode in general and was just wondering what leaded you to put it into a container as it gets shipped in many ways i just wanted to collect arguments you helped me a lot. I personal run everything in my own platform no docker or such stuff. 

Thanks a lot

**Comment by grzegorzk** [comment]
@lemanschik ah, I misunderstood your question :) I like to run software on my system in container so I don't get host polluted with dependencies, and also I like to run software in isolation. With vscode plugins I also get the same environment each time I run it on different machines (though, of course, this would not be a problem if you are installing directly on host).
